import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [list, setList] = useState([])

  const handleClick = (event) => {
    const newClick = {
      clientX: event.clientX,
      clientY: event.clientY
    }
    setList((prev) => [...prev, newClick])
  }

  return (
    <>
      <Head>
        <title>Playing Around with N13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <div
            onClick={handleClick}
            className='bg-zinc-300 h-full w-full fixed'>
            {list.map((item, index) => (
              <span key={index} className="bg-red-600 w-6 h-6 rounded-full absolute" style={{ left: item.clientX, top: item.clientY }} />
            ))}
          </div>
        </header>
      </main>
    </>
  )
}
