import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Playing Around with N13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <h2>Front-end Interview Challenges</h2>
        </header>
      </main>
    </>
  )
}
