import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [list, setList] = useState([])

  const handleClick = (event) => {
    const newClick = {
      clientX: event.clientX,
      clientY: event.clientY
    }
    setList((prev) => [...prev, newClick])
  }

  const handleUndo = () => {
    const newList = [...list].slice(0, -1)
    setList(newList)
  }

  const handleRedo = () => {
    console.log(list)
  }

  return (
    <>
      <Head>
        <title>Playing Around with N13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className='fixed justify-center items-center top-4 w-full z-10 flex gap-2'>
          <button
            onClick={handleUndo}
            className="bg-red-400 py-2 px-3 rounded-md font">Undo
          </button>
          <button
            onClick={handleRedo}
            className="bg-red-400 py-2 px-3 rounded-md font">Redo
          </button>
        </div>

        <div
          onClick={handleClick}
          className='bg-zinc-300 h-full w-full fixed'>
          {list.map((item, index) => (
            <span key={index} className="bg-red-600 w-6 h-6 rounded-full absolute" style={{ left: item.clientX, top: item.clientY }} />
          ))}
        </div>
      </main >
    </>
  )
}
